### ISSUE TITLE
Most up to date?

### ISSUE THREAD

**Issue by ghost** [WAZAAAAA0/antimicro#1]
Was the original Antimicro page deleted? I was wondering if the source you put up is the most up to date. Sorry about opening this as an Issue, I don't know if GitHub has forums or anything like that.

**Comment by WAZAAAAA0** [comment]
Yes the main repository got removed for this reason: https://github.com/Ryochan7/antimicro-packaging/issues/1
I uploaded the source code of the last released version (2.21), but this fork is technically the last source code available: https://github.com/7185/antimicro but nobody knows for sure if it works since... well, it has never been used in a release.

EDIT: Actually, THIS repo has the latest source code. Please move any discussion there: https://github.com/AntiMicro/antimicro

**Comment by WAZAAAAA0** [comment]
@TheLastProject test1

**Comment by WAZAAAAA0** [comment]
Thisisatest

1

<img width="192" height="110" alt="Image" src="https://github.com/user-attachments/assets/44e55c12-c100-4638-9ff9-bc29d0067775" />

2

![Image](https://github.com/user-attachments/assets/4f2d3846-fc4f-443d-93e7-84fc2d962241)

3

<img width="32" height="32" alt="Image" src="https://github.com/user-attachments/assets/b60f328d-afdb-4f46-a736-663123d5baa9" />

4

<img width="128" height="128" alt="Image" src="https://github.com/user-attachments/assets/69e988b3-b174-459c-a1e2-60dfb00de14e" />

**Comment by WAZAAAAA0** [comment]
@D4n2021 just pinging to say I didn't ignore your Mozilla review replies, sent an email to the address listed in https://sites.google.com/view/dan-tech-blog but maybe it got lost in the ether
